### ISSUE TITLE
igv session file not working for windows

### ISSUE THREAD

**Issue by lzj1769** [SchulzLab/EpigenomeAnalysisTutorial-2020#8]
![image](https://user-images.githubusercontent.com/9947922/91563173-b7da4280-e93e-11ea-950e-3ba7dc269ecc.png)

**Comment by skarunan** [comment]
@lzj1769 Actually @DennisHeck found out that IGV session was not working even in Mac. 

We found out the cause is in the XML file there was an absolute path for certain tracks. We modified the XML files accordingly today mid noon, and I uploaded a new image. It should work with a new pull of the image.

EDIT: It's not enough to just pull and start/run an existing container. You need to execute the docker run command again, after changing the name of the container...

Eg.: docker run -it -P --name epigenomics2 -v ~/container-data:/data sivarajank/epigenomics_tutorial:latest
